### ISSUE TITLE
entered the site but got an error

### ISSUE THREAD

**Issue by demaico** [SKane315/bypy#1]
1. Firefox
2. Chrome
3. Exit
            
Option: 2
Traceback (most recent call last):
  File "/Users/maicovandenbossche/Downloads/bypy-master/main.py", line 40, in <module>
    main(sys.argv[1])
  File "/Users/maicovandenbossche/Downloads/bypy-master/main.py", line 37, in main
    Query.ch(link)
  File "/Users/maicovandenbossche/Downloads/bypy-master/src/query.py", line 24, in ch
    driver = webdriver.Firefox()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by 5ynthy** [comment]
Did you install the web driver for the browser you're trying to use? Also, make sure it is added to your path

**Comment by demaico** [comment]
It is installed at /usr/local/bin (mac)

**Comment by 5ynthy** [comment]
Which driver are you using? The chromedriver or geckodriver?

**Comment by demaico** [comment]
The chromedriver

**Comment by 5ynthy** [comment]
When you type `chromedriver --version`, What's the output?

**Comment by 5ynthy** [comment]
Ohh wait, it's an issue with my code! I'm sorry! Fixing it ASAP!

**Comment by 5ynthy** [comment]
Alright, I fixed it! I'm very sorry about the inconvenience. Please try now and tell me if it works or not. Thank you!

**Comment by demaico** [comment]
It opened a window for a second but got error again, video here 
[error.zip](https://github.com/SKane315/bypy/files/4362964/error.zip)

**Comment by 5ynthy** [comment]
As you can see from: ![here](https://user-images.githubusercontent.com/55880108/77228476-7dbc8600-6bd3-11ea-836c-071e05ba346e.png) the chrome driver doesn't support your chrome version. Try to update the version of your chrome browser to a compatible version

**Comment by demaico** [comment]
I've got the newest, but installed the previous driver that works on this version and I have this error 
![Screen Shot 2020-03-21 at 15 31 10](https://user-images.githubusercontent.com/31244653/77228655-05c96e00-6b89-11ea-93cf-4f13dbbce9c8.png)

**Comment by SKane315** [comment]
Hmm weird... may I have the link you're trying to bypass?

**Comment by 5ynthy** [comment]
Alright, I updated the script. Please update it and try again and tell me if it works or not. I'm very sorry for the inconvenience...

**Comment by demaico** [comment]
It's just a test I'm doing the site will be http://maetrimal.com/40Vf

**Comment by demaico** [comment]
Still error

**Comment by 5ynthy** [comment]
Did you update the script? I tried it with your url and it worked completely fine for me. Also, may I see the error?

**Comment by demaico** [comment]
yes I downloaded the new version and used it
![Screen Shot 2020-03-21 at 15 58 13](https://user-images.githubusercontent.com/31244653/77229208-cb61d000-6b8c-11ea-9a30-e076e6469e2a.png)

**Comment by demaico** [comment]
![Screen Shot 2020-03-21 at 15 58 48](https://user-images.githubusercontent.com/31244653/77229223-de74a000-6b8c-11ea-9397-d3cffead4fdc.png)

**Comment by 5ynthy** [comment]
Did you update the whole thing? Because the main.py isn't the file that got updated

**Comment by demaico** [comment]
I did the pip install again but donno if that's what you meant

**Comment by 5ynthy** [comment]
That doesn't update the files. You have to redownload the repository

**Comment by demaico** [comment]
I reinstalled everything and have this going on
Last login: Mon Mar 23 00:00:07 on ttys001
Maicos-MacBook-Pro:~ maicovandenbossche$ ls
Applications		Documents		Movies			Pictures		PycharmProjects		bypy			sherlock
Creative Cloud Files	Downloads		Music			Projects		Untitled.txt		geckodriver.log
Desktop			Library			Parallels		Public			VirtualBox VMs		mamp
Maicos-MacBook-Pro:~ maicovandenbossche$ cd bypy
Maicos-MacBook-Pro:bypy maicovandenbossche$ ls
README.md		main.py			requirements.txt	src
Maicos-MacBook-Pro:bypy maicovandenbossche$ pyhton3 main.py http://maetrimal.com/40Vf
-bash: pyhton3: command not found
Maicos-MacBook-Pro:bypy maicovandenbossche$ python3 main.py http://maetrimal.com/40Vf
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from src.query import Query
  File "/Users/maicovandenbossche/bypy/src/query.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Maicos-MacBook-Pro:bypy maicovandenbossche$ python3 main.py http://maetrimal.com/40Vf in /usr/local/bin/chromedriver
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from src.query import Query
  File "/Users/maicovandenbossche/bypy/src/query.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Maicos-MacBook-Pro:bypy maicovandenbossche$
Maicos-MacBook-Pro:bypy maicovandenbossche$
Maicos-MacBook-Pro:bypy maicovandenbossche$ pip3 install -r requirements.txt
Collecting selenium==3.141.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
     |████████████████████████████████| 911kB 2.0MB/s
Collecting urllib3==1.25.8 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.25.8
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Maicos-MacBook-Pro:bypy maicovandenbossche$ ls
README.md		main.py			requirements.txt	src
Maicos-MacBook-Pro:bypy maicovandenbossche$ python3 main.py http://maetrimal.com/40Vf

=============
Made by SKane
=============

1. Firefox
2. Chrome
3. Exit

Option: 2
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main(sys.argv[1])
  File "main.py", line 36, in main
    Query.ch(link)
  File "/Users/maicovandenbossche/bypy/src/query.py", line 30, in ch
    for i in skip.split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by 5ynthy** [comment]
May I see the code of your installed file in `bypy/src/query.py`?

**Comment by demaico** [comment]
![Screen Shot 2020-03-23 at 04 00 36](https://user-images.githubusercontent.com/31244653/77276439-f3e7e800-6cba-11ea-8083-ee2a844ecf3b.png)

**Comment by 5ynthy** [comment]
Hmm... that is very odd... it works totally fine for me. Even with the exact same url you are trying to bypass...

**Comment by demaico** [comment]
weird, unfortunate
